export {default as MainPage} from './MainPage'
export {default as AuthPage} from './AuthPage'
export {default as RegisterPage} from './RegisterPage'
export {default as LoadingPage} from './LoadingPage'
export {default as AdminPage} from './AdminPage'